export const ANECDOTES = 'ANECDOTES';
export const GET_ANECDOTE = 'GET_ANECDOTE';
export const MY_ANECDOTES = 'MY_ANECDOTES';
export const ANECDOTES_OF_USER = 'ANECDOTES_OF_USER';
export const CREATE_ANECDOTE = 'CREATE_ANECDOTE';
export const REMOVE_ANECDOTE = 'REMOVE_ANECDOTE';
export const UPDATE_ANECDOTE = 'UPDATE_ANECDOTE';