export const ERROR_LOGIN = 'ERROR_LOGIN';
export const ERROR_REGISTER = 'ERROR_REGISTER';
export const LOADING = 'LOADING';
export const RESPONSE_PROFILE = 'RESPONSE_PROFILE';
export const SUCCESS_ACTION = 'SUCCESS_ACTION';
export const ERROR_CREATE = 'ERROR_CREATE';
export const ERROR_UPDATE_PROFILE = 'ERROR_UPDATE_PROFILE';
export const ERROR_UPDATE = 'ERROR_UPDATE';